- .travis.yml
- dotenv.py
- setup.py
Support Python 2.6, since it's trivial.
> Enable Python 2.6 support

- dotenv/__init__.py
- dotenv/main.py
- tests/test_core.py
- Add `find_dotenv` method that will try to find a .env file by
(a) guessing where to start using `__file__` or the working
directory -- allowing this to work in non-file contexts such as
IPython notebooks and the REPL, and then (b) walking up the dir-
ectory tree looking for the specified file -- called `.env` by
default. This is a bit like the "filthy magic" employed by
django-dotenv[1] to serve the same purpose, and allows the user
to write `load_dotenv(find_dotenv())` in many contexts.
- Add test for new function
[1] https://github.com/jpadilla/django-dotenv/blob/master/dotenv.py#L44-L46
> Add method to walk up directories looking for .env

- README.rst
- dotenv/cli.py
- dotenv/main.py
- tests/test_cli.py
- tests/test_core.py
I needed this so much that made a PR without even asking if you would be intereseted on the feature, hope you like it.
Includes proper testing.
> Support POSIX parameter expansion

- README.rst
- dotenv/cli.py
- dotenv/main.py
- tests/test_cli.py
This fixes #35 
Note, that this is still far from an SH-compatible parser, but this at least fixes this particular issue.
To be an SH-compatible parser, these kinds of things would have to be fixed:
- `HELLO=WORLD` shoud be treated differently from `HELLO= WORLD`
- `HELLO=${WORLD}` should be treated differently from `HELLO='${WORLD}'`
- The parsing of a POSIX variable should take a previous POSIX variable in precedence over an environment variable.
- And so on.
> Naive single quotes

- dotenv/main.py
- tests/test_cli.py
Without this changes the new test that I added fail. So for example, you have in your `.env` password with special characters:
```
PASSWORD="}=&~{,(\5%{&;"
```
But using package it return: `}=&~{,(%{&;` (Missing `\5`)
> Added support for special characters

- README.rst
- dotenv/main.py
- tests/test_core.py
Because this warning _scares_ me and our team more often than _helps_ us.
Probably, similar changes should be applied to other functions.
`verbose` option for `load_dotenv`, which will log any error messages
Warning `File .env not found` disabled by default.
Several investigations are here: motdotla/dotenv#154 (be careful, NodeJS thread)
> Disable ".env not found" warning by default

- README.rst
Also fixes typo in "Related" projects link
`dump-env` takes an `.env.template` file and some optional environmental variables to create a new `.env` file from these two sources.
Why do we need such a tool? Well, this tool is very helpful when your CI is building ``docker`` (or other) images.
[Previously](https://github.com/wemake-services/wemake-django-template/blob/6a7ab060e8435fd855cd806706c5d1b5a9e76d12/%7B%7Bcookiecutter.project_name%7D%7D/.gitlab-ci.yml#L25) we had some complex logic of encrypting and decrypting files, importing secret keys and so on.
Now we can just create secret variables for our CI, add some prefix to it, and use `dump-env` to make our life easier.
> Adds dump-env to the related projects

- README.rst
As mentioned in #82, the `\n` is required for proper parsing of multiline values. This example must be covered in the readme, This PR does just that..
> fixes #82 by improving doc for mutiline variable example

- dotenv/__init__.py
`import dotenv` takes long time when IPython is installed.
This affects pypa/pipenv now.  ([ref](https://paste.ubuntu.com/26409167/))
This pull request imports `dotenv.ipython` lazily to avoid overhead.
> Import IPython lazily

- README.rst
- dotenv/main.py
- tests/test_core.py
Backwards-compatible API for `parse_dotenv()` that allows a stream having a dotfile to be parsed.
The other option would be to save my already-existing stream in disk and providing the filepath, but this could have security and performance considerations.
> Allows `parse_dotenv(stream=StringIO())`

- .gitignore
- README.rst
- dotenv/__init__.py
- dotenv/cli.py
- dotenv/compat.py
- dotenv/ipython.py
- dotenv/main.py
- setup.cfg
- tests/test_core.py
> Allow `load_dotenv` and `dotenv_values` to work with StringIO objects

- dotenv/cli.py
The title says it all. I use python-dotenv with Fabric and want to be able to control the  quote mode from "get_cli_string".
Thanks for an awesome library :-)
> Allow quote mode to be specified in get_cli_string

- .travis.yml
- README.rst
Having valid RST is important so that Pypi's web interface interprets the RST correctly and display `long_description` in a pretty format. Right now, the Pypi page looks pretty ugly:
https://pypi.python.org/pypi/python-dotenv
This pull request fixes the errors, and also adds a simple test to avoid this problem in the future.
> Fix RST errors in README.rst and test for errors

- dotenv/main.py
- tests/test_core.py
This is a fix for #108, which is due I believe to the fact that `find_dotenv` does not go back far enough in the call stack to find the calling module, which causes its path searching starting point to be itself (i.e. `main.py`).
@theskumar, @RazerM
> Fix to enable loading from current directory

- dotenv/main.py
- tests/test_core.py
`parse_line` currently implements the stripping of the `"export "` prefix incorrectly, such that any variable name prefix consisting of the characters ` eoprtx` will get stripped too.
This means that for example `export port_number = 8000` will get parsed as `_number = 8000`.
> Bugfix: parse_line incorrectly strips "export " prefix

- dotenv/main.py
- tests/test_cli.py
This is an alternative to PR#103
When using "dotenv set", a new line is not put after the replaced key, causing key/values to end up on the same line.
To reproduce:
Create an env file with some keys and values int it:
`test.env`
```
key1="value1"
key2="value2"
key3="value3"
```
run:
```
dotenv -f test.env set key1 value11
```
`test.env` now looks like:
```
key1="value11"key2="value2"
key3="value3"
```
Also updated tests for `set_key` to reflect changes.
> Add new line when updating key with "set_key" (Alternative to PR#103)

- dotenv/main.py
The function `find_dotenv` try to find a file named `.env`, if there is a directory named `.env` by coincidence, then `DotEnv._get_stream` will  raise IOError.
use `os.path.isfile` instead of `os.path.exists`.
> fix bug: DotEnv._get_stream raise IOError when  `.env` is a directory rather than a file

- README.md
Not sure if this was intentional or not, but I'm pretty sure that EGGS is normally spelt with two Gs and one S.
> EGSS → EGGS

- .travis.yml
Remove python 3.3 environment in travis config file.
> Drop Python 3.3 support

- dotenv/main.py
- tests/test_cli.py
- tests/test_core.py
This adds support for:
* multiline values (i.e. containing newlines or escaped \n), fixes #89
* backslashes in values, fixes #112
* trailing comments, fixes #141
* UTF-8 in unquoted values, fixes #147
This supersedes a previous pull-request, #142, which would add support for
multiline values in `Dotenv.parse` but not in the CLI (`dotenv get` and `dotenv
set`).
The internal change is significant but I have added a lot of test cases to reduce the risk of breaking anything.  Previous test cases are still present, so I wouldn't expect any major backward incompatibility.
I have written detailed commit messages and made my code as clear as possible.  Let me know if anything should be improved.  I'll be happy to fix anything unsatisfactory.
> Add support for newlines, backslashes, trailing comments and unquoted UTF-8

- dotenv/main.py
- tests/test_core.py
In Python, `\s` also matches newlines.  This would cause newlines to be
consumed by the equal sign matcher, resulting in the next line being
considered as a value.
For instance, the following would be parsed as `[("FOO", "BAR=b")]`
instead of `[("FOO", ""), ("BAR", "b")]`.
```bash
FOO=
BAR=b
```
Fixes #157.
> Fix parsing of variable without a value

- tests/test_cli.py
While working on another PR I noticed that running the test suite was leaving a `tests/dotenv` file.  There appeared to be two test functions that were creating that file but not deleting it when done.
> Deleted some temporary files that CLI tests were creating

- requirements.txt
- tests/conftest.py
- tests/fixtures.py
- tests/test_cli.py
- tests/test_core.py
The test suite had the following issues:
* A failing test would leave files in the `tests` directory, causing
other tests to fail unexpectedly.
* Even successful tests would require clean up code like `sh.rm(...)` to
avoid leaving test files.  This was easy to forget as shown by #153.
* The same test file would be used for several tests, making them unsafe
to run in parallel.
This commit fixes that by using the `dotenv_file` and `tmp_path`
fixtures whenever the filesystem is required.  The advantage of those
fixtures is that they use unique test directories, which are eventually
cleaned up.
The `tmp_path` fixture is preferred to the `tmpdir` fixture because
`tmpdir` relies on `py.path`, a library in "maintenance mode".
> Isolate test files

- src/dotenv/main.py
- tests/test_core.py
In Python 2 the extension returned by `__file__` can be either `.pyc` or `.pyo` in addition to `.py`, which means #109 does not always work in Python 2.
This fixes #130 and might be related to #124.
I added the `current_file` variable because modifying `__file__` didn't seem like a good idea (if it's even possible, I didn't try it).
> Special __file__ handling for Python 2 (fixes #130)

- README.md
- src/dotenv/main.py
> Allow passing of encoding to load_dotenv and dotenv_values (Pr/144)

- README.md
- src/dotenv/compat.py
- src/dotenv/main.py
- tests/test_core.py
This encodes environment keys and values for `os.environ` in Python 2
and fixes the following issues:
* Values loaded from `.env` being `unicode` whereas regular values being
`str` (i.e. `bytes`) in Python 2.
* Error when loading `.env` with UTF-8 characters in Python 2.
* `# type: ignore` hiding the issue from the type checker.
`sys.getfilesystemencoding()` is used because it seems to match the
encoding used for environment variables with Python 2.  Since it can
apparently return `None`, we fall back to a default encoding (UTF-8
here) if that's the case.
I tested this on Windows where `"mbcs"` is the file system encoding.
Hopefully, this will also work on other systems.
Closes #121. Closes #176.
> Fix unicode/str inconsistency in Python 2

- README.md
- src/dotenv/main.py
Previously, this checked whether `__file__` was defined in `globals()`.  `globals()`
is tied to the current module, so this will always be defined. Fix this by
importing `__main__` and asking whether it has `__file__` defined. This approach is
outlined in https://stackoverflow.com/a/2356420.
Thanks @andrewsmith
> Improve interactive mode detection

- README.md
HI,
Dynaconf heavily uses `python-dotenv` 
https://dynaconf.readthedocs.io
https://github.com/rochacbruno/dynaconf
> Adding Dynaconf to related projects

- .travis.yml
- src/dotenv/compat.py
- src/dotenv/parser.py
- tests/test_core.py
- tox.ini
The dependency on the `typing` package is now optional for Python 3.4. This commit runs (part of) the test suite when that package is absent, to ensure the dependency isn't reintroduced accidentally.
> Run tests also when typing is absent

- src/dotenv/main.py
- src/dotenv/parser.py
- tests/test_parser.py
This prints a warning such as the following on stderr (`logging.warning`) when part of the .env file can't be parsed:
```
Python-dotenv could not parse statement starting at line 2
```
I think it's OK to use the "warning" level because such an error means that something should be fixed by the user.
Note that Python-dotenv will continue to parse the file and won't interfere in any other way with the application using it.
I've also added some commits to fix the CI (linting in the code and the manifest).
Fixes #204
> Print warning on malformed lines in .env file

- README.md
https://github.com/pypa/pipenv/issues/3610
> [docs] Note about variables needing to be wrapped in {}

- CHANGELOG.md
- src/dotenv/main.py
- src/dotenv/parser.py
- tests/test_parser.py
- Don't print warning when key has no value.
- Reject more malformed lines (e.g. "A: B").
> Fix handling of no-value and malformed lines

- requirements.txt
- src/dotenv/main.py
- tests/test_core.py
- tox.ini
Problems with the `warnings` module:
* Undesirable output in tests, although it could be filtered out.
* Output unsuited for users: shows source code of Python-dotenv.  Users
don't know what to do with that.
* Meant for programming issues (e.g. deprecation) rather than
runtime issues (file not found).
Problems with the `logging` module:
* Slightly less easy to test, unlike warnings with
`catch_warnings(record=True)`, because you need to use the `mock`
package for compatibility with Python 2.
Despite this last issue, I think it makes more sense to use the
`logging` module as a base for warnings.
Of course, `logging` is not suited to all forms of output, so this
change doesn't mean `logging` has to be used everywhere.  For instance,
if we want to improve the output of the `dotenv` CLI …
> Use logging instead of warnings

- src/dotenv/main.py
- tests/test_core.py
Implements the option to skip the interpolation of variables in the _value side_ of the entry.
In my case, this is necessary to fix a bug in `docker-compose`. You can check the open PR [here](https://github.com/docker/compose/pull/6937)
> Add control over interpolation

- .travis.yml
- CHANGELOG.md
- src/dotenv/main.py
- tests/test_main.py
> Fix escaping of quoted values written by `set_key`

- CHANGELOG.md
- src/dotenv/cli.py
- tests/test_cli.py
Dotenv run currently crashes when we use a variable without value (ie with None as value).
Exemple of problematic dotfile:
```
a=b
c
```
This PR filter out such variables from the dict that is eventually given to Popen, avoiding the crash.
> Fix dotenv run crashes on variable without values

- CHANGELOG.md
- src/dotenv/parser.py
- tests/test_main.py
- tests/test_parser.py
This also simplifies tests and adds test cases for `set_key`.
Closes #235.
> Remove warning when last line is empty

- requirements.txt
- tox.ini
This pins `click==7.0` and `mypy==0.761` since these are the lastest working ones.
This should fix `master`
> Pin click==7.0 and mypy==0.761

- CHANGELOG.md
- README.md
- src/dotenv/main.py
- tests/test_main.py
When interpolation is active, variable expansion can use a default value, like in Bash.
> Add support for POSIX default values

- CHANGELOG.md
- src/dotenv/main.py
- tests/test_main.py
As per #256 when users refer to an environment variable that is defined at the current environment and re-defined at the file, the interpolation order always favors the os.environ value.
It does not make sense to favor the environment variable as it is already re-defined in the .env file context. This PR reverts the order of getting these values from the proper dicts. Also i have added a test case to expose such behavior
> fix interpolation order

- CHANGELOG.md
- src/dotenv/main.py
- tests/test_main.py
Example problematic file:
```bash
hello=hi
greetings=${hello}
goodbye=bye
greetings=${goodbye}
```
It would result in `greetings` being associated with the empty string
instead of `"bye"`.
The problem came from the fact that bindings were converted to a dict,
and so deduplicated by key, before being interpolated.  The dict would
be `{"hello": "hi", "greetings": "${goodbye}", "goodbye": "bye"}` in the
earlier example, which shows why interpolation wouldn't work: `goodbye`
would not be defined when `greetings` was interpolated.
This commit fixes that by passing all values in order, even if there are
duplicated keys.
Closes #197
> Fix empty expanded value for duplicate key

- CHANGELOG.md
- src/dotenv/parser.py
While `typing` was added in 3.5.0, `typing.Text` was only added in
3.5.2, and so causes an `AttributeError`, not an `ImportError`
exception.
Replaces #262.
Closes #261.
> Fix import error on Python 3.5.0 and 3.5.1

- CHANGELOG.md
- README.md
- src/dotenv/cli.py
- src/dotenv/main.py
- tests/test_cli.py
- tests/test_main.py
- Add `--export` option to `set` to make it prepend the binding with
`export`.
- Make `set` command create the `.env` file in the current directory if
no `.env` file was found.
Replaces #270.
> Add --export to `set` and make it create env file

- CHANGELOG.md
- src/dotenv/parser.py
- tests/test_parser.py
If a value is unquoted and has two or more adjacent spaces (like in `a=b c`), the parser would detect an error.  This commit fixes that.
Tabs are now also considered like space characters in this case and I added relevant test cases.
Closes #276
> Fix parsing of unquoted values with two spaces

- .travis.yml
- CHANGELOG.md
- README.md
- src/dotenv/main.py
- src/dotenv/variables.py
- tests/test_main.py
- tests/test_variables.py
> Fix variable expansion order with override=False

- CHANGELOG.md
- src/dotenv/main.py
The default value for the `encoding` parameter of `load_dotenv` and `dotenv_values` is now `"utf-8"` instead of `None` (which selected the encoding based on the user's locale).  It is passed directly to `io.open`.
The rationale for this change is that the encoding of a project file like `.env` should not depend on the user's locale by default.  UTF-8 makes sense as the default encoding since it is also used for Python source files.  The main drawback is that it departs from `open`'s default value of `None` for the `encoding` parameter.
The default value of `None` was a source of confusion for some users. The Flask and Docker Compose projects already use `encoding="utf-8"` to enforce the use of UTF-8 and avoid that sort of confusion.
This is a breaking change but only for users with a …
> Use UTF-8 as default encoding

- CHANGELOG.md
- src/dotenv/cli.py
- tests/test_cli.py
This makes it possible to not override previously defined environment variables when running `dotenv run`.  It defaults to `--override` for compatibility with the previous behavior.
Closes #302.
> Add --override/--no-override flag to "dotenv run"

- CHANGELOG.md
- src/dotenv/cli.py
- tests/test_cli.py
The `get` subcommand would return `key=value`, which is impractical to retrieve the value of a key in a script.  Since the `key` is already known by the caller, there is no point in showing it.
This also makes the output consistent with the documentation for the subcommand.
Closes #307.
> Make `dotenv get` only show the value instead of key=value

- README.md
In the existing example, the name `stream` is undefined, causing a
NameError.
> Fix stream parse example in README.md

- CHANGELOG.md
- tests/test_cli.py
Hey,
I want to update dotenv to 0.17.0 in Fedora, but realized the two newly introduced tests started failing in the build process.
This happens because defining `_env` [replaces the existing environment](https://amoffat.github.io/sh/sections/special_arguments.html#env), effectively unsetting many variables (which, in my case, means losing information where to look for the module to import). Instead of creating completely new contents, I propose copying existing environment and adding the tested key-value on the top of it. 
This will not affect the existing test suite but can help other packagers.
> Fix tests for build environment relying on `PYTHONPATH`

- README.md
Added django-environ-2 because this project is developing independently from joke2k's django-environ.
> Add django-environ-2 to the Related Projects list

- tests/conftest.py
This notably prevents the file `.nx_file` from being created and not removed after running tests.  That file could also lead to confusing test failures when changing and testing the code of python-dotenv.
> Avoid leaving any file after running tests

- .github/workflows/test.yml
- CHANGELOG.md
- setup.py
- tox.ini
This is a big change.  It will make it possible to simplify the code, add more features, improve the robustness and lower the barrier to new contributions.
As per [Python's packaging documentation][doc], the `python_requires` keyword argument needs `setuptools >= 24.2.0` (released in 2016) and will only have en effect for `pip >= 9.0.0` (released in 2016 as well).
See #329 for more information.
[doc]: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
> Require Python >= 3.5

- CHANGELOG.md
- src/dotenv/main.py
- tests/test_main.py
This applies to the `load_dotenv` and `dotenv_values` functions.  This makes it possible to pass a file stream such as `open("foo", "r")` to these functions.
Closes #308.
> Allow any text stream (`IO[str]`) as `stream`

- CHANGELOG.md
`codespell --ignore-words-list="nd"`
> CHANGELOG.md: Fix typos discovered by codespell

- CHANGELOG.md
- src/dotenv/main.py
- tests/test_main.py
Sometimes, the source file doesn't have a trailing newline.  If we add a new binding in such a case, we need to add a newline before the new binding.
Closes #360.
> Add missing trailing newline before adding new entry with `set_key`

- CHANGELOG.md
- src/dotenv/main.py
- tests/test_main.py
The parameter already exists for `dotenv_values` and `load_dotenv` and has the same meaning.
Closes #378.
> Add encoding parameter to {get,set,unset}_key

- CHANGELOG.md
- setup.py
Not sure why or when but the string syntax for entry points does not
seem to work correctly anymore (no scripts are installed).  Use
the explicit list-in-dict syntax instead.
> Fix installing entry points

- CHANGELOG.md
- setup.cfg
Python 2 is no longer supported and so our wheels should not be marked as universal.
Closes #383.
> Don't mark wheels as universal

- setup.py
- src/dotenv/main.py
Since python 2 support has been dropped, there is no difference between `io.open` and `open`. And it is recommended to use `open` over `io.open`. Just replacing all the occurrences of `io.open` with `open` in this PR.
> Use `open` instead of `io.open`

- README.md
- src/dotenv/main.py
> Improve documentation for variables without a value

- tests/test_ipython.py
Packaging IPython for more "exotic" architectures poses a serious
problem to Gentoo developers.  Make it possible to easily run the test
suite without it installed by skipping the few tests requiring it.
> Skip test_ipython if IPython is not available

- requirements.txt
- tests/test_ipython.py
- tests/test_main.py
- tox.ini
Python 3 has a built-in version of mock available as unittest.mock.
Use it instead of installing the third-party package.
> Use built-in unittest.mock instead of third-party mock

- .github/workflows/release.yml
- CONTRIBUTING.md
- MANIFEST.in
- requirements-docs.txt
- requirements.txt
Build and deploy docs to gh-pages as part of
tag release.
> chore: add GitHub Actions for deploying docs

- README.md
`parse_it` is similar to `dynaconf` but focus more on giving the enduser the ability to use his preferred way to set config, `.env` being one of the choices it's using and makes available to endusers
> Add `parse_it` to Related Projects

- .github/workflows/test.yml
- setup.py
- src/dotenv/main.py
- tox.ini
> Drop Python 3.5 and 3.6 and upgrade GA

- README.md
- src/dotenv/cli.py
- tests/test_cli.py
The default is simple, which is backwards compatible.
--format=json will display the list as a json dict
resolves #405
> feat(cli) add --format= option to list command

- src/dotenv/main.py
- tests/test_main.py
I just changed the with block to `dest = ...` since `delete=False` was preventing it from being cleaned up anyway, and then set a default value for `dest` in case an error happens earlier.
> fix: out of scope error when "dest" variable is undefined #413

- src/dotenv/variables.py
Changed some old style code to newer syntax, and also simplified some expressions.
> Modernize variables code

- tests/test_ipython.py
IPython would complain about:
DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
> Fix IPython test warning about deprecated `magic`

- src/dotenv/__init__.py
- src/dotenv/cli.py
Use f-strings, make some code more concise and change docstrings to double quotes according to[ PEP257](https://peps.python.org/pep-0257/).
> Improve conciseness of cli.py and __init__.py

- src/dotenv/cli.py
- tests/test_cli.py
The error message would previously be confusing. For example, `dotenv -f . list` would print:
Error: Invalid value: Path "." does not exist.
Instead, we now print:
Error opening env file: [Errno 21] Is a directory: '.'
I used this opportunity to slightly refactor the I/O code (e.g. fewer system calls and possible race conditions) for those two subcommands (`get` and `list`).
> Improve error message for `get` and `list` commands when env file can't be opened

- src/dotenv/cli.py
This is seen in some situations with dynaconf where the system under test starts from a src code directory that got moved around or deleted during operation.
https://github.com/dynaconf/dynaconf/issues/853
```
$ cat REPRODUCER_DIRECT.sh
#!/bin/bash
rm -rf /tmp/foobar
mkdir -p /tmp/foobar
cd /tmp/foobar
rm -rf /tmp/foobar
echo "PWD:$(pwd)"
dotenv --help
```
> Handle situations where the cwd does not exist.

- README.md
I usually use dotenv, but I learned about this alternative from libhunt. It seems to have similar goals. (I'll probably stick with dotenv.)
> Add python-decouple as a related project

- src/dotenv/main.py
- tests/test_zip_imports.py
I encountered this issue when loading my codebase into Spark via the --py-file option. Basically, if a file in a zip archive tries to call `load_dotenv()`, and that file is then imported, it will cause an error. Hopefully the test cases are self-explanatory!
> Gracefully handle code which has been imported from a zipfile

- tests/conftest.py
- tests/test_cli.py
- tests/test_ipython.py
- tests/test_main.py
Replace all filesystem code with `pathlib.Path` objects and operations. Nothing is changed in the source code (and thus in the usage of the lib), only the tests have less boilerplate.
Usually all `*_file` string objects are replaced with `*_path` Path objects.
> Use pathlib.Path in tests

- README.md
This PR converts all HTTP links in the README.md file to HTTPS.
It fixes issue #473
> fixes #473 Use https in README links

- src/dotenv/main.py
Hello!
I am one of the maintainers of [gradio](https://github.com/gradio-app/gradio), an os library for developing web applications in python. One of gradio's features is the ability to automatically refresh the web page when the python source code is modified without having to restart the server.
Users started reporting that gradio applications that use `load_dotenv` would fail when reloaded (See https://github.com/gradio-app/gradio/issues/5468). I think the root cause is related to the fact that load_dotenv is being reloaded on a separate thread.
I traced this to the `is_interactive` check and added a fix that works for gradio and I don't think introduces any unintended changes to `python-dotenv`.
Curious to hear your thoughts. Thank you!
> Allow modules using load_dotenv to be reloaded when launched in a separate thread

- src/dotenv/main.py
Currently, if an error is raised while using files from the rewrite function, then the temporary file is deleted before closing it.
This is okay on unix, but unlinking open files causes an error on Windows.
> Fix error handling in the rewrite function

- src/dotenv/main.py
add below to `find_dotenv`, so that when user run `load_dotenv()` in pdb or other debugger, they can still load the `.env` file in current working directory, otherwise current `frame_filename` will goes to `Lib/bdb.py`
```python
def _is_debugger():
return sys.gettrace() is not None
if usecwd or _is_interactive() or _is_debugger() or getattr(sys, "frozen", False):
...
```
> add _is_debugger so load_dotenv will work in pdb
