- README.md
Obvious for most, but not all...
> Formatting .env file documentation

- README.md
@theskumar, I've corrected a typographical error in the documentation of the [python-dotenv](https://github.com/theskumar/python-dotenv) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.
> Fixed typographical error, changed acomplish to accomplish in README.

- Makefile
- dotenv/cli.py
- dotenv/main.py
- tests/test_cli.py
> Support for configurable quoting mode, references #15

- README.rst
s/is not support/is not supported/
> Fixed a typo

- README.rst
Implicit hyperlink syntax plus a couple of typos fixed in README.rst.
> README.rst minor syntax/typo fixes

- requirements.txt
It's used in `tests/fixtures.py` file: 
```
from click.testing import CliRunner
```
Check also Travis build: https://travis-ci.org/theskumar/python-dotenv/jobs/236861670
> Added `click` module to requirements.txt file

- README.rst
- dotenv/__init__.py
- dotenv/cli.py
- setup.py
- tests/test_cli.py
closes https://github.com/theskumar/python-dotenv/issues/66
> Optional cli

- README.md
environs is a framework-agnostic envvar-parsing solution.
It uses python-dotenv under the hood for reading .env.
> Add environs

- dotenv/main.py
- tests/test_cli.py
> Fixed stderr/-out/-in redirection.

- setup.py
- tests/test_cli.py
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>
> Fix ResourceWarning: unclosed file in setup.py and test_cli.py

- README.md
Just wanted to help proofread!
> Update README.md (minor typos and grammar)

- CHANGELOG.md
- src/dotenv/main.py
- src/dotenv/parser.py
- tests/test_parser.py
> Fix handling of lines with just a comment

- setup.py
https://github.com/altendky/pyqt5-tools/issues/38
WIP for:
> Set UTF-8 encoding when reading files in setup.py

- .travis.yml
Your code coverage is broken, this commit would fix it
> fix coveralls error

- README.md
> Refine Python version constraint in readme example

- README.md
Reflects changes made in PR https://github.com/theskumar/python-dotenv/pull/258.
> Fix interpolation order in README.md

- .travis.yml
- setup.py
- tox.ini
Changes:
- Add Python 3.9 to TravisCI config
- Add Python 3.9 to supported languages in `setup.py`
- Edit `tox.ini`
> Add python 3.9 to CI

- setup.cfg
> Fix setuptools warning

- README.md
> Fix documentation of `dotenv set`

- setup.py
- src/dotenv/__main__.py
- src/dotenv/cli.py
> feat(cli): add support for invocations via 'python -m'

- src/dotenv/__init__.py
> __init__.py

- src/dotenv/main.py
- src/dotenv/parser.py
Move comment type hints to code type hints, use f-strings and modernize overall code to newer more concise Python syntax.
> Modernize main.py and parser.py code

- .github/workflows/test.yml
- requirements.txt
- setup.py
- tests/test_cli.py
- tox.ini
`click` and `sh` both don't support 3.7 anymore.
> Drop support for python 3.7, add python 3.12-dev
